# -*- coding: utf-8 -*-
"""Sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cT5IeC4ntaEW47jNM38bVVkjirg7w-7k

***Sets:*** Are unordered collections of unique elements used to store multiple items in a single variable, that support efficient search, insert, and delete operations.

# **Variable Definition**

## Definition by {} operators:
"""

fruits = {"apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"}
print(fruits)
print(type(fruits))

"""## Definition by Set function :"""

fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"))
print(fruits)
print(type(fruits))

"""## Definition a Set from a String:"""

string_set = set("Hello")
print(string_set)

"""## Defining an Empty set:"""

fruits = set()
print(fruits)
print(type(fruits))

"""##Rule 1 -Sets elements are unsorted:"""

fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"))
fruits1 = {"lemon", "banana", "apple", "grapes", "cherry", "orange", "pear"}
print(fruits == fruits1)

"""## Rule 2 -Sets elements are unique:

1.   Notice that eventhoug "Hello" has two "l"s only one is stored
2.   Same occurs when you have an elemente defined twice
"""

string_set = set("Hello")
print(string_set)
fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon", "apple"))
print(fruits)

"""## An error ocurs when trying to define a list inside the set:"""

fruits = set(['apple', 'banana', 'cherry',[1,2,3]])
print(string_set)

"""# **Functions and Methods**

## In function

x in s :  test x for membership in s
"""

fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"))
print("apple" in fruits)
print("garlic" in fruits)

"""## Not in function

**x not in s:**
Test x for non-membership in s
"""

fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"))
print("apple" not in fruits)
print("garlic" not in fruits)

"""## Len function

**len(s):** Number of elements in set s (cardinality)
"""

my_set = set()
my_set.add(1)
my_set.add(2)
my_set.add(3)
my_set.add(4)
my_set.add(5)
my_set.add(2) # Notice that 2 is not added twice
print(len(my_set))

while len(my_set) > 4:
  print(my_set.pop())

"""IsDisJoin method"""

animals = {"Dog","Horse","Cat", "Robin", "Swallow"}
birds = {"Robin", "Swallow"}
fish = {"Salmon", "Tuna"}
print(animals.isdisjoint(birds))
print(animals.isdisjoint(fish))

"""#**Add**

**s.add(x):**
adds element x to set s
"""

my_set = set()
my_set.add(1)
my_set.add(2)
my_set.add(3)
my_set.add(4)
my_set.add(5)
my_set.add(2) # Notice that 2 is not added twice
print(my_set)

"""## Examples

###Adding Members from List
Implement a function which takes as a parameter List and add elements to a Set and return a set.

**Example:**

my_list = [3,4,5,1,1,3,4,9,8]

adding_set(my_list)

**Output:**
{1, 3, 4, 5, 8, 9}

**Note:** The order of elements might be different.
"""

def adding_set(p_list):
    my_set = set()
    for i in p_list:
        my_set.add(i)
    return my_set
my_list = [3,4,5,1,1,3,4,9,8]
adding_set(my_list)

"""### Remove Duplicates
How can we remove duplicates from given List using Set?

**Example:**

my_list = ["apple", "apple", "orange", "grape", "grape", "orange", "apple"]

**Output:**['grape', 'apple', 'orange']
"""

my_list = ["apple", "apple", "orange", "grape", "grape", "orange", "apple"]
my_set = set(my_list)
my_list = list(my_set)

"""# **Deleting**

## Clearing a set
"""

fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"))
fruits.clear()
print(fruits)

"""## Removing elements"""

fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"))
print(fruits)
fruits.remove("banana")
print(fruits)

"""## Discarding elements

The remove method returns and error message when the element to be removed is not in the set while discard doesn't retur an error
"""

fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"))
fruits.remove("mango")

fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"))
print(fruits)
fruits.discard("mango")
fruits.discard("banana")
fruits.discard("mango") #Notice mango is not in the set
print(fruits)

"""## Discarding using a List"""

fruits = {"apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"}
print(fruits)
remove_list = ["apple", "cherry", "orange","Dragaon Furit"]
for item in remove_list:
  fruits.discard(item)
print(fruits)

"""## Pop method

**s.pop():**
Remove and return an arbitrary element from s; raises KeyError if empty
"""

fruits = set(("apple", "banana", "cherry", "grapes", "pear", "orange", "lemon"))
print(fruits)
print(fruits.pop())
print(fruits)

"""##Examples:

### Delete Restricted Items:
Set of items and set of restricted items are given, based on the beach type (family or normal) the list of items should be printed to the console. Restricted items are not allowed to family beach and everything else can be taken to normal beach except drugs.

general_items = {
    "Sand toys",
    "Beach towels",
    "Beach umbrella",
    "Camp chair",
    "Snacks",
    "Hats",
    "Camera",
    "Sunglasses",
    "Alcholic Drinks",
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects"
}

restricted_items = {
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects",
    "Amplified Audio",
    "Drugs"
    }


**Example Input**

Select Beach Type (1 - Family beach, 2 - Normal Beach): 1

**Example Output**

See below the list of items that you can take.
    
* Non Alcholic Drinks
* Sand toys
* Snacks
* Sunglasses
* Hats
* Beach umbrella
* Beach towels
* Camp chair
* Camera

**My solution:**
"""

general_items = {
    "Sand toys",
    "Beach towels",
    "Beach umbrella",
    "Camp chair",
    "Snacks",
    "Hats",
    "Camera",
    "Sunglasses",
    "Alcholic Drinks",
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects"
}

restricted_items = {
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects",
    "Amplified Audio",
    "Drugs"
    }
option = int(input("Select Beach Type (1 - Family beach, 2 - Normal Beach): "))
if option == 1:
    print_set =set(general_items)
    for item in restricted_items:
        print_set.discard(item)
else:
    print_set = set(general_items)
    print_set.discard("Drugs")
print("See below list of items that you can take.")
while len(print_set) > 0:
    print(print_set.pop())

"""**Course solution:**"""

general_items = {
    "Sand toys",
    "Beach towels",
    "Beach umbrella",
    "Camp chair",
    "Snacks",
    "Hats",
    "Camera",
    "Sunglasses",
    "Alcholic Drinks",
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects"
}

restricted_items = {
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects",
    "Amplified Audio",
    "Drugs"
}
option = int(input("Select Beach Type (1 - Family beach, 2 - Normal Beach): "))
if option == 1:
        for item in restricted_items:
            general_items.discard(item)
else:
    general_items.discard("Drugs")
print("See below list of items that you can take.")
for item in general_items:
    print(f"\t{item}")

"""**Solution using the instead of discar the remove with error handling**"""

general_items = {
    "Sand toys",
    "Beach towels",
    "Beach umbrella",
    "Camp chair",
    "Snacks",
    "Hats",
    "Camera",
    "Sunglasses",
    "Alcholic Drinks",
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects"
}
restricted_items = {
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects",
    "Amplified Audio",
    "Drugs"
}
option = int(input("Select Beach Type (1 - Family beach, 2 - Normal Beach): "))
if option == 1:
        for item in restricted_items:
            try:
                general_items.remove(item)
            except KeyError:
                print(f"Skipping {item}, because it's not in the set")
else:
    try:
        general_items.discard("Drugs")
    except KeyError:
                print(f"Skipping Drugs, because it's not in the set")
print("See below list of items that you can take.")
for item in general_items:
    print(f"\t{item}")

"""# **Unions**

**s.union(t) s | t:**
New set with elements from both s and t

## Union Method
"""

fruits = {"apple", "banana", "cherry"}
vegetables = {"tomato", "potato", "onion"}
print(fruits.union(vegetables))
print(fruits,vegetables)

"""##Union | operator"""

fruits = {"apple", "banana", "cherry"}
vegetables = {"tomato", "potato", "onion"}
print(fruits|vegetables)
print(fruits,vegetables)

"""## Set definition using Union"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
print(f"fruits Set: {fruits}")
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(f"vegetables Set: {vegetables}")
orchard = fruits.union(vegetables) #Orchard is updated using update withou impacting the other sets
print(f"Orchard Set: {orchard}")
print(f"fruits Set: {fruits}")
print(f"vegetables Set: {vegetables}")

"""## Set definition using | operator"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
print(fruits)
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(vegetables)
orchard = fruits | vegetables #Orchard is updated using the update operator withou impacting the other sets
print(orchard)
print(fruits)
print(vegetables)

"""## Examples:

### Combine Sets
Two sets are given write a program which creates a new set with all items from both sets by removing duplicates. And print final set to the console.

**Set1:** {10,20,30,40,50}

**Set2:** {60,20,50,70}

**Output:**
{70, 40, 10, 50, 20, 60, 30}

**Note** - The order of elements might be different
"""

set1 = {10,20,30,40,50}
set2 = {60,20,50,70}
#Using Union
print(set1.union(set2))
#Using Pipe operator
print(set1|set2)

"""### Union List of Sets
Implement a function which takes list of sets as a parameter and returns one set which includes all elements from the given list of sets.

list_of_sets = [
    {10,20,30,40,50},
    {"apple", "orange","limon","pear"},
    {"London", "Berlin", "Paris"},
    {"Python", "Java", "Swift"},
    {10, "ten", "20", 20}
]

**Input:** convert_ls(list_of_sets)

**Output:**
{'limon', 'pear', 'Java', 'orange', 10, 'Swift', 'apple', 20, 'Python', 'Paris', 30, '20', 'London', 'ten', 40, 50, 'Berlin'}
"""

list_of_sets = [
    {10,20,30,40,50},
    {"apple", "orange","limon","pear"},
    {"London", "Berlin", "Paris"},
    {"Python", "Java", "Swift"},
    {10, "ten", "20", 20}
]
def convert_ls(p_list_of_sets):
    my_set = set()
    for item in p_list_of_sets:
        my_set = my_set.union(item)
    return my_set
print(convert_ls(list_of_sets))

"""#**Intersection**

**s.intersection(t)**
**s & t:**
new set with elements common to s and t

## Intersection method
"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(fruits.intersection(vegetables))
print(fruits,vegetables)

"""## Intersetion using the & operator"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(fruits & vegetables)
print(fruits,vegetables)

"""## Set definition from an intersection"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
intersect = set.intersection(fruits,vegetables)
intersect2 = fruits & vegetables
print(intersect)
print(intersect2)

"""## Set definition from a range"""

set1 = set(range(20))
print(set1)
set2 = set(range(0,20,2))
print(set2)
set3 = set(range(0,20,3))
print(set3)
print(set.intersection(set1,set2,set3))
print(set1 & set2 & set3)



"""##Examples:

###Find Numbers Divisible by 3 and 4

Implement a function which takes a parameter N and returns Set of numbers which are divisible by 3 and 4 between 0 and N.   

**Example Input:** divisible_by_3and4(100)

**Output:**
{0, 96, 36, 72, 12, 48, 84, 24, 60}

**My Solution**
"""

def divisible_by_3and4(n):
    set3 = set()
    set4 = set()
    for item in range(0, n):
        if item % 3 == 0:
            set3.add(item)
    for item in range(0, n):
        if item % 4 == 0:
            set4.add(item)
    return set.intersection(set3,set4)
print(divisible_by_3and4(100))

"""**Courses Solution**"""

def divisible_by_3and4(n):
    set3 = set(range(0,n,3))
    set4 = set(range(0,n,4))
    return set.intersection(set3,set4)
print(divisible_by_3and4(100))

"""**Solution Modified it to have 2 divisible parameters**

"""

def divisible_by(n,num1,num2):
    set1 = set(range(0,n,num1))
    set2 = set(range(0,n,num2))
    return set.intersection(set1,set2)
print(divisible_by(100,6,7))

"""### Find Preposition
Implement a function which takes a quote as a parameter to find out which given prepositions have been used in the quote. The function should return the set of prepositions that are used in the quote.

**Example:**
quote = '''Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.'''

prep = {"as", "but", "by", "for", "in", "of", "on", "to", "with"}

find_prep(quote)

**Output:** {'of', 'to'}

**My Solution**
"""

quote = """Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do."""
prep = {"as", "but", "by", "for", "in", "of", "on", "to", "with"}

def find_prep(p_quote):
    set_quote = set(p_quote.split(" "))
    return set.intersection(set_quote, prep)
print(find_prep(quote))

"""**Course's Solutions**"""

quote = """Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do."""
prep = {"as", "but", "by", "for", "in", "of", "on", "to", "with"}

def find_prep(p_quote):
    set_quote = set(p_quote.split())
    return prep.intersection(set_quote)
print(find_prep(quote))

"""#**Substraction**

## Difference method
**s.difference(t)**
**s - t:**  New set with elements in s but not in t
"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(fruits.difference(vegetables))
print(vegetables.difference(fruits))
print(fruits,vegetables)

"""## Difference using - operator"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(fruits - vegetables)
print(vegetables - fruits)
print(fruits,vegetables)

"""### Example"""

# My solution:
general_items = {
    "Sand toys",
    "Beach towels",
    "Beach umbrella",
    "Camp chair",
    "Snacks",
    "Hats",
    "Camera",
    "Sunglasses",
    "Alcholic Drinks",
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects"
}

restricted_items = {
    "Non Alcholic Drinks",
    "Sigarettes",
    "Sharp Objects",
    "Amplified Audio",
    "Drugs"
    }
option = int(input("Select Beach Type (1 - Family beach, 2 - Normal Beach): "))
if option == 1:
    print_set =set(general_items-restricted_items)
else:
    print_set = set(general_items - {"Drugs"})
print("See below list of items that you can take.")
while len(print_set) > 0:
    print(print_set.pop())

"""## Examples:

**Difference of More than two Sets**
There are three Sets are given. Write a program that finds the difference of them.

a = {1, 2, 3, 40, 50, 300, 400}
b = {10, 20, 30, 40, 300}
c = {100, 200, 300, 400}

**Output:**
{1, 2, 3, 50}
"""

a = {1, 2, 3, 40, 50, 300, 400}
b = {10, 20, 30, 40, 300}
c = {100, 200, 300, 400}
print(set.difference(a,b,c))

"""##Symmetric Difference

**s.symmetric_difference(t)** |
**s ^ t:**

New set with elements in either s or t but not both

### Symmetric difference method
"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
sym_diff = fruits.symmetric_difference(vegetables)
print(sym_diff)

"""### Symetric difference using ^ operator"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
sym_diff2 = fruits ^ vegetables
print(sym_diff2)

"""#**Update**

**s.update(t)**

**s |= t:** Return set s with elements added from t

## Update method
"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
print(fruits)
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(vegetables)
fruits.update({"Dragon Fruit"}, {"Jack Fruit"})
print(fruits)

"""## Union Update using the |= operator"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
print(fruits)
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(vegetables)
fruits |= vegetables
print(fruits)
fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
vegetables |= fruits
print(vegetables)

"""## Intersect Update"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
print(f"fruits Set: {fruits}")
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(f"vegetables Set: {vegetables}")
intersect = fruits.intersection(vegetables)
print(f"intersect Set: {intersect}")
print(f"fruits Set: {fruits}")
print(f"vegetables Set: {vegetables}")
#Intersection is created and there is no change to the original sets
print("****IntersectUpdate occured****")
intersect = fruits.intersection_update(vegetables)
print(f"intersect Set: {intersect}")
print(f"vegetables Set: {vegetables}")
print(f"fruits Set: {fruits}")
#Intersection set is created but becuase the method doesn't returns a value then none is printed and there is change
#to the original fruit set

"""## Intersect Update using &= operators"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
print(f"fruits Set: {fruits}")
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
fruits &= vegetables
print(f"vegetables Set: {vegetables}")
print(f"fruits Set: {fruits}")
#The intersection is now updated int the original fruit set

"""##Difference Update"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
print(f"fruits Set: {fruits}")
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
print(f"vegetables Set: {vegetables}")
diff_set = fruits.difference(vegetables)
print(f"Difference Set: {diff_set}")
print(f"fruits Set: {fruits}")
print(f"vegetables Set: {vegetables}")
#DifferenceUpdate is created and there is no change to the original sets
print("****Differeance_Update occured****")
diff_set = fruits.difference_update(vegetables)
print(f"diff_update Set: {diff_set}")
print(f"vegetables Set: {vegetables}")
print(f"fruits Set: {fruits}")
#DifferenceUpdate set is created but becuase the method doesn't returns a value then none is printed and there is change
#to the original fruit set

"""## Difference Update using &= operators"""

fruits = {"apple", "banana", "cherry", "orange", "cucumber", "greap"}
print(f"fruits Set: {fruits}")
vegetables = {"tomato", "potato", "onion", "cucumber", "broccoli", "pepper"}
fruits -= vegetables
print(f"vegetables Set: {vegetables}")
print(f"fruits Set: {fruits}")
#The difference is now updated int the original fruit set

"""# Sub Sets and Super Sets

**s.issubset(t)** **s <= t:**
Test whether every element in s is in t

---
**s.issuperset(t)** **s >= t:**
test whether every element in t is in s

## Subset method
"""

animals = {"Dog","Horse","Cat", "Robin", "Swallow"}
birds = {"Robin", "Swallow"}
print(animals.issubset(birds))
print(birds.issubset(animals))
print(animals.issubset(animals))

"""## Subset using <= operators"""

animals = {"Dog","Horse","Cat", "Robin", "Swallow"}
birds = {"Robin", "Swallow"}
print(animals <= birds)
print(birds <= animals)
print(animals <= animals)

"""## Super Set"""

animals = {"Dog","Horse","Cat", "Robin", "Swallow"}
birds = {"Robin", "Swallow"}
print(animals.issuperset(birds))
print(birds.issuperset(animals))
print(animals.issuperset(animals))

"""## Superset using <= operators"""

animals = {"Dog","Horse","Cat", "Robin", "Swallow"}
birds = {"Robin", "Swallow"}
print(animals >= birds)
print(birds >= animals)
print(animals >= animals)