# -*- coding: utf-8 -*-
"""Dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpZ2cbLQM4tlo7q3XfqR-ne94Oxaw47S

A dictionary is a data structure that uses a key either str or int type followed by a value
Example: key:value :: miller: person who owns or works in a corn mill

# Creatin a dictionary
"""

my_dictionary = {
    'Miller':'a person who owns or works in  a corn mill',
    'Programer':'a person who writes computer programs',
    'App':'an application, especially as downloaded by a user to a mobile device'
    }
print(my_dictionary)

"""## Empty Dictionary"""

my_dictionary = {}
print(my_dictionary)
# another way to define an empty dictionary
my_dictionary = dict()
print(my_dictionary)

"""## Defining a dictionary and then emptying it out"""

print(my_dictionary)
my_dictionary = dict()
print(my_dictionary)

"""## Accessing the values in a dictionary"""

my_dictionary = {
    'Miller':'a person who owns or works in  a corn mill',
    'Programer':'a person who writes computer programs',
    'App':'an application, especially as downloaded by a user to a mobile device'
    }
print(my_dictionary['Miller'])

"""## Using an integer as key in the dictionary"""

my_dictionary = {
    'Miller':'a person who owns or works in  a corn mill',
    'Programer':'a person who writes computer programs',
    'App':'an application, especially as downloaded by a user to a mobile device',
    123:'one two three'
    }
print(my_dictionary['Miller'])
print(my_dictionary[123])

"""# Insert/Update elements in the dictionary

## Defining an empty dictionary and incerting one element at the time
"""

my_dictionary = {}
print(my_dictionary)
my_dictionary['Miller'] = 'a person who owns or owns a corn mill'
print(my_dictionary)
my_dictionary['Programer'] = 'a person who writes computer programs'
print(my_dictionary)
my_dictionary['App'] = 'an application, especially as downloaded by a user to a mobile device'
print(my_dictionary)
my_dictionary[123] = 'one two three'
print(my_dictionary)

"""## Updating the data in a dictionary"""

my_dictionary = {
    'Miller':'a person who owns or works in  a corn mill',
    'Programer':'a person who writes computer programs',
    }
print(my_dictionary)
my_dictionary['Programer'] = 'a developer who writes computer programs and apps'
print(my_dictionary)

"""## Any miss spelling in the key will generate a new entry in the dictionary"""

print(my_dictionary)
my_dictionary['Programerr'] = 'a developer who writes computer programs and apps'
print(my_dictionary)

"""## **Exercise**
### Generate Dictionary:
Implement a function which takes integer number (n) as a parameter and returns dictionary with keys from 1 to n and values are square of the numbers from 1 to n.
### Example:
generate_dictionary(5)
### Output:
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
"""

def generate_dictionary(n):
    dictionary = {}
    for number in range(1,n+1):
        dictionary[number] = number*number
    return dictionary
print (generate_dictionary(25))

"""# Travers/Search for elements:

## Printing the keys in a dictionary using a loop
"""

my_dictionary = {
    'Miller':'a person who owns or works in  a corn mill',
    'Programer':'a person who writes computer programs',
    'App':'an application, especially as downloaded by a user to a mobile device',
    123:'one two three'
    }
for item in my_dictionary:
    print(item)

"""## Printing the values in a dictionary using a loop"""

for item in my_dictionary:
    print(my_dictionary[item])

"""## Printing both keys and values in a dictionary"""

for key in my_dictionary:
    print(f"{key}: {my_dictionary[key]}")

"""##Searching if the key exists in the dictionary"""

for key in my_dictionary:
    if key == 'App':
        print("App: It exists in the dictionary")
        print(my_dictionary[key])

"""## Exercise

### **Multiply Dictionary Items:**
Implement a function which takes dictionary as a parameter and returns multiplication of values of this dictionary.

### Example:
my_dict = {"One" : 1, "Two" : 2, "Three" : 3, "Four" : 4}

multiply_values(my_dict)

### Output: 24
"""

my_dict = {
    "One" : 1,
    "Two" : 2,
    "Three" : 3,
    "Four" : 4
    }
def multiply_values(my_dict_p):
    result = 1
    for key in my_dict_p:
        result *= my_dict_p[key]
    return result
print(multiply_values(my_dict))

"""
###**Student Grades:**
Implement a function which takes a dictionary as a parameter in which student scores are stored and converts their scores to grades and return it as new dictionary.

###This is the scoring criteria:
*   Scores 85 - 100: Grade = "Outstanding"
*   Scores 65 - 84: Grade = "Good"
*   Scores 50 - 64: Grade = "Acceptable"
*   Scores 50 lower: Grade = "Fail"

###Example:
student_scores = {
  "John": 90,
  "Edy": 68,
  "Marry": 88,
  "Ewan": 79,
  "Park": 62,
}
convert_grade(student_scores)

###Output:
{
 'John': 'Outstanding',
 'Edy': 'Good',
 'Marry': 'Outstanding',
 'Ewan': 'Good',
 'Park': 'Acceptable'
}"""

student_scores = {
    "John": 90,
    "Edy": 68,
    "Marry": 88,
    "Ewan": 79,
    "Park": 62,
    }
def convert_grade(dict_p):
    result = dict()
    for key in dict_p:
        if dict_p[key] > 84:
            result[key] = "Outstanding"
        elif dict_p[key] > 64:
            result[key] = "Good"
        elif dict_p[key] > 49:
            result[key] = "Acceptable"
        else:
            result[key] = "Failed"
    return result
print(convert_grade(student_scores))

"""# Removing elements from a diccionary

##Pop method removes a specified item from the dictionary and returns it
"""

print(my_dictionary)
result = my_dictionary.pop('Programer')
print(my_dictionary)
print(result)

"""## You can add a second parameter to pop method so that it is retuned in case the sent key does not exist in the dictionary"""

result = my_dictionary.pop('Programmer',None)
print(result)

"""Popitem removes the last item on the list"""

my_dictionary = {
    'Miller':'a person who owns or works in  a corn mill',
    'Programer':'a person who writes computer programs',
    'App':'an application, especially as downloaded by a user to a mobile device',
    123:'one two three'
    }
result = my_dictionary.popitem()
print(result)
print(my_dictionary)

"""Deleting an item on the dictionary using a key"""

my_dictionary = {
    'Miller':'a person who owns or works in  a corn mill',
    'Programer':'a person who writes computer programs',
    'App':'an application, especially as downloaded by a user to a mobile device',
    123:'one two three'
    }
print(my_dictionary)
del my_dictionary['Miller']
print(my_dictionary)

"""Clear method empties the dictinary"""

my_dictionary = {
    'Miller':'a person who owns or works in  a corn mill',
    'Programer':'a person who writes computer programs',
    'App':'an application, especially as downloaded by a user to a mobile device',
    123:'one two three'
    }
print(my_dictionary)
my_dictionary.clear()
print(my_dictionary)

"""## **Exercise**
### Rename Key:
Write a program which renames the key in the dictionary, you need to rename key city to address in the following dictionary.

my_dict = {
    "name": "Edy",
    "age":30,
    "salary": 5000,
    "city": "London"
}

### Output:
{
    "name": "Edy",
    "age":30,
    "salary": 5000,
    "address": "London"
}
"""

my_dict = {
    "name": "Edy",
    "age":30,
    "salary": 5000,
    "city": "London"
}
print(my_dict)
my_dict['address'] = my_dict.pop('city')
print(my_dict)

"""# IN/NOT IN operators

## In function looks for a key in the dictionary and returns true or false
"""

my_dictionary = {
    1: 'One',
    2: 'Two',
    3: 'Three',
    4: 'Four'
    }
print(1 in my_dictionary)
print(5 in my_dictionary)

"""## The IN operator looks only for keys and not the values of items in the dictionary"""

print("One" in my_dictionary)

"""## **Exercise**
###Count Characters in a Word:
Implement a function that takes a String as a parameter and returns a dictionary with characters as keys from the String and values are the occurrence of characters in the String. Basically we are counting the occurrence of characters in a given string and returning it as output in Dictionary.

###Example:
count_character("BABACDAS")

###Output:
{
 'B': 2,
 'A': 3,
 'C': 1,
 'D': 1,
 'S': 1
}
"""

def count_character(str_p):
    result = {}
    for character in str_p:
        if character in result:
            result[character] += 1
        else:
            result[character] = 1
    return result

print(count_character("BABACDAS"))

"""# Nesting Dictionaries

## Nesting a list inside a dictionary
"""

programing_language = {
    "Elshad" : ["Python", "Java", "C#"],
    "Renad" : "Scratch",
    "Edy" : "Python"
    }
print(programing_language)

"""## Nesting a dictionary inside a dictionari"""

programing_language = {
    "Elshad" : {"favorite_languages" : ["Python", "Java", "C#"],
                "experience": 10
                },
    "Renad" : {"favorite_languages": ["Scratch","Python"],
               "experience" : 2
               },
    "Edy" : "Python"
    }
print(programing_language)

"""## Nesting Dictionary inside list"""

programing_language = [
    {"user_name":"Elshad",
     "favorite_languages" : ["Python", "Java", "C#"],
    "experience": 10
    },
    {"user_name":"Renad",
     "favorite_languages": ["Scratch","Python"],
     "experience" : 2
    },
    {
     "user_name":"Edy",
     "favorite_languages": ["Python"],
     "experience" : 3
    }
]
print(programing_language)

"""## **Exercise**
###Nesting Dictionary Exercise:
Implement a function that adds new key value pairs to the programming_language list. You can see the list below in which there is only two dictionaries, after insert method, there should be three dictionaries. After insertion we need to print programming_language list to the console.

programming_language = [
    {"user_name" : "Elshad",
     "favorite_languages" : ["Python", "Java", "C#"],
     "experience": 10
    },
    {"user_name":"Renad",
     "favorite_languages" : ["Scratch","Python"],
     "experience" : 2
    },
]
###Example:
add_new_user("Edy", ["Java", "Kotlin", "Swift"], 10)

###Output:
[
 {'user_name': 'Elshad',
  'favorite_languages': ['Python', 'Java', 'C#'],
  'experience': 10
 },
 {'user_name': 'Renad',
  'favorite_languages': ['Scratch', 'Python'],
  'experience': 2
 },
 {'user_name': 'Edy',
  'favorite_languages': ['Java', 'Kotlin', 'Swift'],
  'experience': 10
 }
]
"""

import pprint
programming_language = [
    {"user_name" : "Elshad",
     "favorite_languages" : ["Python", "Java", "C#"],
     "experience": 10
    },
    {"user_name":"Renad",
     "favorite_languages" : ["Scratch","Python"],
     "experience" : 2
    },
]
def add_new_user(user_name_p,programming_language_list,experience_p):
    temp_dictionary = {
        "user_name" : user_name_p,
        "favorite_languages" : programming_language_list,
        "experience" : experience_p
    }
    programming_language.append(temp_dictionary)

pprint.pprint(programming_language)
add_new_user("Edy", ["Java", "Kotlin", "Swift"], 10)
pprint.pprint (programming_language)

"""# Missing key in a dictionary"""

items ={
    "computer" : 10,
    "printer" : 8,
    "mouse" : 15,
    "webcam" : 12,
    "router" : 10
    }
quantity = items.get("mouse")
print(f"The ammount of mouse in the store is: {quantity}")
quantity = items.get("keyboard") #Here the default is none
print(f"The ammount of keyboards in the store is: {quantity}")
print(items)
quantity = items.get("keyboard",0) #Here we asign 0 to be teh default
print(f"The ammount of keyboards in the store is: {quantity}")
quantity = items.get("keyboard","Item does not exists in the store") #Here we add a message
print(f"The ammount of keyboards in the store is: {quantity}")
quantity = items.setdefault("keyboard") #Here we add the item and set it to none by default
print(f"The ammount of keyboards in the store is: {quantity}")
print(items)
quantity = items.setdefault("keyboard",0) #Here we add the item and set it to 0
print(f"The ammount of keyboards in the store is: {quantity}")
print(items)

"""# Fromkeys and keys methods"""

custom_dict = {
    0 : "zero",
    1 : "one",
    2 : "two",
    3 : "three",
    4 : "four",
    5 : "five",
    6 : "six",
    7 : "seven",
}
devices_list = ["phone", "tablet", "computer", "TV"]
new_dict = {}.fromkeys(devices_list,0)
print(new_dict)
keys = custom_dict.keys()
print(keys)
for item in custom_dict:
    print(item)
for item in custom_dict.keys(): #this does the same but it's more readable
    print(item)

"""## **Exercise**
### Group Value Types:
Implement a function which takes a List a parameter and groups them according to their data types (integer or string) and return dictionary.
### Hint:
-Use isinstance() function to check data type.

-Use fromkeys() method to solve this challenge
### Example:
custom_list = [10, "one", "two", "ten", 20, 30, "five", 40, "nine", 50]
group_types(custom_list)
### Output:
{
 10: 'Integer',
 'one' : 'String',
 'two' : 'String',
 'ten' : 'String',
 20 : 'Integer',
 30 : 'Integer',
 'five' : 'String',
 40 : 'Integer',
 'nine' : 'String',
 50 : 'Integer'
}
"""

def group_types(p_list):
    new_dict = {}.fromkeys(p_list)
    for item in new_dict:
        if isinstance(item, int):
            new_dict[item] = "Integer"
        else:
            new_dict[item] = "String"
    print(new_dict)


custom_list = [10, "one", "two", "ten", 20, 30, "five", 40, "nine", 50]
group_types(custom_list)

"""# Items method"""

custom_dict = {
    0 : "zero",
    1 : "one",
    2 : "two",
    3 : "three",
    4 : "four",
    5 : "five",
    6 : "six",
    7 : "seven",
}
for item in custom_dict:
    print(item, custom_dict[item])
print()
for key, values in custom_dict.items():
    print(key, values)
print(custom_dict.items())

"""## **Exercise**
### Length of Dictionary Values:
Implement a function which takes a dictionary as a parameter and returns new dictionary.  In new dictionary the keys remain same but values will be another nested dictionary. Nested dictionary's keys will be values from original dictionary and values will be length of values from original dictionary. (I know it is confusing, see example below you will understand it :) )
### Example:
names_dict = {
    1 : "Elshad",
    2 : "Renad",
    3 : "Johanna",
    4 : "Appmillers"
}
value_length(names_dict)
### Output:
{
    1: {'Elshad': 6},
    2: {'Renad': 5},
    3: {'Johanna': 7},
    4: {'Appmillers': 10}
}
"""

names_dict = {
    1 : "Elshad",
    2 : "Renad",
    3 : "Johanna",
    4 : "Appmillers"
}
def value_length(p_dict):
    new_dict = dict.fromkeys(p_dict)
    for key, values in p_dict.items():
        new_dict[key] = {values : len(values)}
    return new_dict
print(value_length(names_dict))

"""# Update Method"""

custom_dict = {
    0 : "zero",
    1 : "one",
    2 : "two",
    3 : "three",
    4 : "four",
    5 : "five",
    6 : "six",
    7 : "seven",
}
custom_dict2 = {
    8 :"eight",
    9 : "nine",
    10 : "ten",
    1 : "new_one",
    2 : "new_two"
}
custom_dict.update(custom_dict2)
for key, values in custom_dict.items():
    print(key, values)

"""##**Exercise**

### Concatenate Three Dictionaries:
Implement a function which takes three dictionaries as parameters and concatenate them into one new dictionary without updating the current ones and returns new dictionary with all elements of these three dictionaries in it.

### Hint:
use update() method of dictionary.

### Example:
dict1={1: "one", 2: "two"}
dict2={3: "three", 4: "four"}
dict3={5: "five", 6: "six"}

concatenate(dict1,dict2,dict3)
### Output:
{
    1: 'one',
    2: 'two',
    3: 'three',
    4: 'four',
    5: 'five',
    6: 'six'
}
"""

dict1={1: "one", 2: "two"}
dict2={3: "three", 4: "four"}
dict3={5: "five", 6: "six"}
def concatenate(p_dict1,p_dict2,p_dict3):
    new_dict = dict()
    new_dict.update(p_dict1)
    new_dict.update(p_dict2)
    new_dict.update(p_dict3)
    return new_dict
print (concatenate(dict1,dict2,dict3))

"""Another way to solve it"""

dict1={1: "one", 2: "two"}
dict2={3: "three", 4: "four"}
dict3={5: "five", 6: "six"}
def concatenate(p_dict1,p_dict2,p_dict3):
    new_dict = dict()
    for dic in (p_dict1,p_dict2,p_dict3):
        new_dict.update(dic)
    return new_dict
print (concatenate(dict1,dict2,dict3))

"""#Values() Method"""

custom_dict = {
    0 : "zero",
    1 : "one",
    2 : "two",
    3 : "three",
    4 : "four",
    5 : "five",
    6 : "six",
    7 : "seven",
    "v" : "five",
}
values = custom_dict.values()
print(values)
custom_dict[8] = "eight"
print(values)
print("five" in values)
print("ten" in values)

values = list(custom_dict.values())
keys = list(custom_dict.keys())
if "five" in values:
    index = values.index("five")
    key = keys[index]
    print(f"{custom_dict[key]} is found with the key {key}")
print()
for key, value in custom_dict.items():
    if value == "five":
       print(f"{custom_dict[key]} is found with the key {key}")

"""## Exercise

### **Remove Empty Items:**
Implement a function which takes as a parameter dictionary and removes empty items from it and return new dictionary. If there is not any empty item in the dictionary it will return itself.
###Example:
custom_dict = {
    "name" : "Elshad",
    "age" : 28,
    "city" : None
}

remove_empty_items(custom_dict)
###Output:
{'name': 'Elshad', 'age': 28}
"""

custom_dict = { "test": None, "wady":24, "name" : "Elshad", "age" : 28, "city" : None }
def remove_empty_items(p_dict):
    new_dic = dict()
    new_dic.update(p_dict)
    for key, value in p_dict.items():
        if value == None:
            del new_dic[key]
    return new_dic
print(remove_empty_items(custom_dict))

# Another way to solve it
def remove_empty_items_2(p_dict):
    for key, value in list(p_dict.items()):
        if value == None:
            del p_dict[key]
    return p_dict
print(remove_empty_items_2(custom_dict))

"""# Copy Method"""

person = {
    "name":"Edy",
    "age" : 20,
    "city" : "London"
}
new_person = person.copy()
new_person["name"] = "Renad"
print(person)
print(new_person)

"""## Shallow Copy"""

person = {
    "name":["Edy", "John", "Ewan"],
    "city" : ["London", "Paris", "Berlin"],
    "language" : ["English","German","French"]
}
new_person = person.copy() #Shallow Copy
print(person["city"])
print(new_person['city'])
new_person["city"].append("New York")
print(person["city"])
print(new_person['city'])

"""### **Exercise**
Merge Two Dictionary
Implement a function which takes as parameter two dictionaries and merge these two dictionaries using Dictionary methods into third dictionary.
###Note:
Loop is not allowed
###Example:
dict1 = {'One': 2, 'Two': 2, 'Three': 3}
dict2 = {'Three': 3, 'Four': 4, 'Five': 5}
merge_dict(dict1, dict2)
###Output:
{'One': 2, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
"""

dict1 = {'One': 2, 'Two': 2, 'Three': 3}
dict2 = {'Three': 3, 'Four': 4, 'Five': 5}
def merge_dict(p_dict1, p_dict2):
    new_dic = p_dict1.copy()
    new_dic.update(p_dict2)
    return new_dic
print(merge_dict(dict1, dict2))

"""##Deep Copy"""

import copy
person = {
    "name":["Edy", "John", "Ewan"],
    "city" : ["London", "Paris", "Berlin"],
    "language" : ["English","German","French"]
}
new_person = person.copy() #Shallow Copy
print(id(person["city"]), person["city"])
print(id(new_person["city"]), new_person["city"])

new_person = copy.deepcopy(person) #Deep Copy
new_person["city"].append("New York")
print(id(new_person["city"]), new_person["city"])
print(id(person["city"]), person["city"])

"""### **Exercise**
Custom Deep Copy for List Values
Implement custom deep copy method for a dictionary where the values are lists.

###Example:
original_dict = {
    "names" : ["Elshad", "John", "Edy"],
    "numbers" : [1,2,3,4,5]
}

copied_dict = deep_copy(original_dict)
copied_dict["names"].append("Jack")
copied_dict["numbers"].append(6)

print(original_dict)
print(copied_dict)
###Output

{
    'names': ['Elshad', 'John', 'Edy'],
    'numbers': [1, 2, 3, 4, 5]
}

{
    'names': ['Elshad', 'John', 'Edy', 'Jack'],
    'numbers': [1, 2, 3, 4, 5, 6]
}
"""

import copy
original_dict = {
    "names" : ["Elshad", "John", "Edy"],
    "numbers" : [1,2,3,4,5]
}
def deep_copy(p_dict):
    new_dict = copy.deepcopy(p_dict)
    return new_dict

copied_dict = deep_copy(original_dict)
copied_dict["names"].append("Jack")
copied_dict["numbers"].append(6)

print(original_dict)
print(copied_dict)

"""### Another Way to solve it"""

original_dict = {
    "names" : ["Elshad", "John", "Edy"],
    "numbers" : [1,2,3,4,5]
}
def deep_copy(p_dict):
    new_dict = dict()
    for key, value in p_dict.items():
        new_value = value.copy()
        new_dict[key] = new_value
    return new_dict
# Main
copied_dict = deep_copy(original_dict)
copied_dict["names"].append("Jack")
copied_dict["numbers"].append(6)

print(original_dict)
print(copied_dict)

"""# New Section"""

my_dict = {
    3 : "three",
    5 : "five",
    9 : "nine",
    1 : "one",
    2 : "two",
    4 : "four"
}
print(3 in my_dict)
print(10 in my_dict)
print("three" in my_dict)
print("three" in my_dict.values())
print("ten" not in my_dict.values())
print(len(my_dict))
print(all(my_dict)) # logical And
print(any(my_dict)) # logical Or
print(max(my_dict))
print(min(my_dict))
print(sorted(my_dict))
print(sorted(my_dict, reverse=True))