# -*- coding: utf-8 -*-
"""Lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvlKJyt2bu0rVp8YX2v7K2TD4Nt8bi63

### Enteros(Int): Los enteros son numeros negativos o positivos que no toman en cuenta fraciones o decimales
"""



#Este programa imprime en pantalla un numero entero que ha sido asignado a una variable
numeroEntero = 2500
print("El numero:",numeroEntero,"es un numero entero" )
#type es una funcion que retorna el tipo de clase de un dato directo o almacenado en una variable
print(type(numeroEntero))

"""## Flotante(float): Aqui se incluyen las fracciones o numeros con decimales"""

#Este programa imprime en pantalla un numero flotante que ha sido asignado a una variable
numeroDecimal = 3.14159265
print("El numero:",numeroDecimal,"es un numero flotante")
print(type(numeroDecimal))

"""## Cadena de caracteres(string): Este es un conjunto de caracteres. Las cadenas estan compuestas por caracteres especiales, letras y numeros"""

#Este programa imprime en pantalla una cadena de caracteres que ha sido asignado a una variable.
palabra = "Hola soy estudiante de la universidad Lead"
print(palabra)
print(type(palabra))

"""## Lista(list): Listas son conjuntos de caracteres separados por una coma y pueden ser accessados por su pocision"""

#Este programa imprime en pantalla una lista que ha sido asignado a una variable.
myList = [1,2,3]
print(myList)
print("myList es de tipo: ",type(myList[0]))
print("Los elementos de mi lista son: ",myList[0],myList[1],myList[2])
myList.append("agregado") #esta funcion predeterminada agrega elementos a la lista
print("Este es el contenido de myList despues deagregar un nuevo valor", myList)
print("El largo de mi lista es de ",len(myList),"elementos") #Esta funcion retorna la longitud de la lista
print("1. ",myList[0])
print("2. ",myList[1])
print("3. ",myList[2])
print("4. ",myList[3])

"""## Tupla(tuple) es una lista que una ves creada sus valores no pueden ser modificados

"""

#Este programa imprime en pantalla una tupla que ha sido asignado a una variable.
myTuple = ("Manzana","Pera","Uva")
print(myTuple)
print(type(myTuple))
print("Mi tupla contiene:",len(myTuple),"elementos")
print("1.",myTuple[0])
print("2.",myTuple[1])
print("3.",myTuple[2])

"""Diccionario (Diccionary/dic)"""

def factorial(p_num):
    if p_num > 0:
        fac = 1
        for x in range(1,p_num+1):
            fac = fac * x
        print(f"The factorial of {p_num} is {fac}")
    else:
        print("Factorial does not exist for negative numbers")
factorial(5)

number_error = "Error, please entere a valid number)"
def is_number(value):
    try:
        value = int(value)
        return True
    except ValueError:
        print(number_error)
        return False
average = 0
count = 0
total = 0
while True:
    num = input("Enter a number: ")
    if num == 'done':
        break
    elif not is_number(num):
        continue
    else:
        total += int(num)
        count += 1
        average = total/count
print(total, count, average)

def check_for_float(p_input):
    try:
        val = float(p_input)
        return val
    except (ValueError, TypeError):
        print("Error, please enter numeric input")
        return False
min = 100000000000000
max = 0
while True:
    num = input("Enter a number: ")
    if num == 'done':
        break
    elif not check_for_float(num):
        continue
    else:
        num = int(num)
        if num < min:
            min = num
        if num > max:
            max = num
print(f"Maximum number: {max}, Minimum number : {min}")

custom_string = 'X-MAPDS-Confidence:0.8475'
data_pos=custom_string.find(':')
data = float(custom_string[data_pos+1:])
print(data)
#

n = 5

for i in range(0, n):
  for j in range(0, i+1):
    print("*", end = ' ')
  print()
for i in range(n,0,-1):
  for j in range(0, i-1):
    print("*", end = ' ')
  print()

def square_list(p_list):
    for index in range(len(p_list)):
      p_list[index] = p_list[index] ** 2

custom_list = [1,2,3,4,5]
square_list(custom_list)
print(custom_list)

custom_list = [1,2,3,4,5,6,7,8,9,10]
print(custom_list[-1::-1])

list1 = [10, 10, 5, 15, 50, 50, 20]
if 50 in list1:
    list1[list1.index(50)] = 5
print(list1)


# First and Last Characters
# Implement a function which takes the string type list as a parameter and returns the count of the number of strings where the string length is 2 or more and the first and the last characters are same.

# Example: list1 = ['cbc', 'xyz', 'aba', '2332', 'abc']

# Output: 3

list1 = ['cbc', 'xyz', 'aba', '2332', 'abc']
count = 0
for word in list1:
    if len(word) >= 2 and word[0] == word[-1]:
        count += 1
print(count)

list1 = [0,1,2,3,4,5,6,7,8,9,10]
list3 = list[1::2]

# Create a List from Two Lists:
# Given two lists create a third list by picking an odd-index element from the first list and even-index elements from the second.

# Input:
# list_one = [4, 12, 16, 21, 24, 28, 32]
# list_two = [5, 10, 15, 20, 25, 30, 35]

# Output:
# [12, 21, 28, 5, 15, 25, 35]

list_one = [4, 12, 16, 21, 24, 28, 32]
list_two = [5, 10, 15, 20, 25, 30, 35]
list3 = list_one[1::2] + list_two[0::2]
print(list3)

"""Remove and Add:
Remove an element at index 4 in a given list and add it to the 2nd position and at the end of the list.

Input: custom_list = [10, 44, 57, 99, 11, 33, 84]

Output:
[10, 44, 11, 57, 99, 33, 84, 11]
"""

custom_list = [10, 44, 57, 99, 11, 33, 84]
x = custom_list.pop(4)
custom_list.insert(2,x)
custom_list.append(x)
print(custom_list)



"""Three Equal Chunks:
Given a list slice it into Three Equal Chunks and reverse each chunk.

sample_list = [21, 55, 18, 33, 24, 22, 68, 35, 79]

Output:
Chunk-1 = [18, 55, 21]
Chunk-2 = [22, 24, 33]
Chunk-3 = [79, 35, 68]
"""

sample_list = [21, 55, 18, 33, 24, 22, 68, 35, 79]
size = int((len(sample_list))/3)
list1 = sample_list[:size]
list2 = sample_list[size:size*2]
list3 = sample_list[size*2:]
print(f"Chunk-1 = {list(reversed(list1))}")
print(f"Chunk-2 = {list(reversed(list2))}")
print(f"Chunk-3 = {list(reversed(list3))}")

"""Print a given list in the format that is shown below using join method."""

custom_list = [1, 2, 3, 4, 5]
string1 = "|".join([str(x) for x in custom_list])
print(string1)

"""Nested Lists:

Example 1
"""

day1 = [11,12,5,2]
day2 = [15,11,6,7]
day3 = [10,13,7.5]
day4 = [12,15,8,6]
all_days = [day1,day2,day3,day4]
print(all_days)
#

"""Example 2"""

my_list = ['a','b',['cc','dd',['eee','fff']],'g','h']
# Accesing one element
print(my_list[2][2][1])
# The changes can be done using the negative values as any string
print(my_list[-3][-1][-1])
print(my_list)
# Updating an element on the table
my_list[1] = 0
print(my_list)
# Updating an element in the third nested list
my_list[2][2][0] = 'aaa'
print(my_list)
#  adding an element to the list
my_list.append('i')
print(my_list)
#  adding an element to the lists first sublist
my_list[2].append('ee')
print(my_list)
#  adding an element to the lists second sublist
my_list[2][2].append('ggg')
print(my_list)
#  Inserting an element to the begining of the lists
my_list.insert(0,'ggg')
print(my_list)
#  Extend comand adds elements to the end of the list
my_list[3].extend([1,2,3])
print(my_list)
#  Deleting the last element of the list
my_list = ['a','b',['cc','dd',['eee','fff']],'g','h']
print(my_list)
del my_list[2][2][0]
print(my_list)

#  Deleting the last element of the list using pop, the diference is that the deleted element can be stored in a var
my_list = ['a','b',['cc','dd',['eee','fff']],'g','h']
print(my_list)
x =  my_list[2][2].pop()
print(my_list)
print(x)
# The len method returns the ammount of elements on the list
my_list = ['a','b',['cc','dd',['eee','fff']],'g','h']
print(my_list)
x =  len(my_list)
print(x)
# To print the items on the list use a loop
print("Items on list")
for item in my_list:
    print(item)
# To print the items in one of the sub lists run a nested loop
print("Items on nested list")
for item in my_list:
    for item2 in item:
        print(item2)
# To print the items in one of the sub lists run a nested loop
print("Items on second nested list")
for item in my_list:
    for item2 in item:
        for item3 in item2:
            print(item3)

"""Add Item in Nested List:
Given a list as shown below and add item 7000 after 5000 and print out final list to the console.

list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]

Output:
[10, 20, [300, 400, [5000, 7000, 6000], 500], 30, 40]
"""

list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].insert(1,7000)
print(list1)

"""Extend Nested List:
Given a nested list and update the list with sub list ["h", "i", "j"] in such a way that it will look like the following list.

list1 = ['a', 'b', ['c', ['d', 'e', ['f', 'g'], 'k'], 'l'], 'm', 'n']

Output:
list1 = ['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']
"""

list1 = ['a', 'b', ['c', ['d', 'e', ['f', 'g'], 'k'], 'l'], 'm', 'n']
list1[2][1][2].append('h')
list1[2][1][2].append('i')
list1[2][1][2].append('j')
print(list1)

# Antother way to solve it
list1 = ['a', 'b', ['c', ['d', 'e', ['f', 'g'], 'k'], 'l'], 'm', 'n']
sublist = ["h", "i", "j"]
list1[2][1][2].extend(sublist)
print(list1)

"""List Addition with Function:
Implement a function which takes two parameters - a list and a value and returns new list with value inserted in it without modifying the original list.

Example:
```
list1 = [1,2,3,4,5]
list2 = custom_insert(list1, 6)
print(list1)
print(list2)
```
Output:
[1,2,3,4,5]
[1,2,3,4,5,6]
"""

def custom_insert(list, x):
    lista = list[:]
    lista.append(x)
    return lista

list1 = [1,2,3,4,5]
list2 = custom_insert(list1, 6)
print(list1)
print(list2)

"""
Concatenate Two Lists in One List Item Wise

Implement a function which takes two lists as parameter and return concatenation of these lists item wise.

Example:
list1 = ["Hello ", "take "]
list2 = ["Dear", "Sir"]

concatenate(list1, list2)

Output:
['Hello Dear', 'Hello Sir', 'take Dear', 'take Sir']"""

def concatenate(list1, list2):
    list3 = []
    for item in list1:
        for item2 in list2:
            list3.append(str(item+item2))
    return list3

list1 = ["Hello ", "take "]
list2 = ["Dear", "Sir"]
print(concatenate(list1, list2))